server:
  port: 8072

spring:
  application:
    name: gateway-service
#  zipkin:
#    baseUrl: http://zipkin:9411
  # Enables the gateway to create routes based on services registered with service discovery
  # (automatically create routes using service id from service discovery)
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      # Enable manual route for organization-service rename path to /orgservice
      # Enable manual route for licensing-service rename path to /licservice
      routes:
        - id: order
          uri: http://order:8091
          predicates:
            - Path=/orderservice/**
          filters:
            - RewritePath=/orderservice/(?<path>.*), /$\{path}
            # gateway doesn’t forward sensitive HTTP headers like cookie,set-cookie, and authorization to downstream services
            - RemoveRequestHeader= Cookie,Set-Cookie

management:
  endpoints:
    web:
      exposure:
        include: "*"
