server:
  port: 3000

spring:
  main:
    # This option is need because spring cloud is not compatible with spring mvc web dependency
    web-application-type: reactive
  application:
    name: gateway-service
  profiles:
    active: dev
#  zipkin:
#    baseUrl: http://zipkin:9411
  # Enables the gateway to create routes based on services registered with service discovery
  # (automatically create routes using service id from service discovery)
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedHeaders: "*"
#            allowedMethods:
#              - GET
#              - POST

# Used to select all endpoints. For example, this to expose everything endpoints over HTTP
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG