routes:
  uri:
    order-service: http://order-service:8050
    payment-service: http://payment-service:8020
    inventory-service: http://inventory-service:8010
    customer-service: http://customer-service:8040
    product-service: http://product-service:8000
    shipping-service: http://shipping-service:8030

spring:
  security:
    oauth2:
      client:
        provider:
          my_provider:
            issuer-uri: http://flowing-keycloak:8080/auth/realms/flowing-realm
        registration:
          my_keycloak:
            provider: my_provider
            client-id: flowing-client
            client-secret: frZzUp0h7fLqZnKGlD7ugUUrXTePsNVD
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/gateway"
            scope: openid, message.read
