######################
# DATASOURCE
######################
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/ecommerce-realm
  datasource:
    url: jdbc:postgresql://postgresql:5432/product_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver