spring:
  kafka:
    bootstrap-servers: kafka:9092
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: validate
#    properties:
#      hibernate:
#        format_sql: true
  datasource:
    url: jdbc:postgresql://postgres:5432/flowing_retail_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

custom:
  flowingretail:
    customer-service:
      host: http://flowing-retail:8080