spring:
  application:
    name: customer-service
  profiles:
    active: dev
server:
  port: 8040

logging:
  level:
    org.springframework: INFO
    # Enable hibernate sql log
    org.hibernate.SQL: DEBUG
    # Log sql parameters. For Hibernate 5 version
    org.hibernate.type.descriptor.sql: TRACE
    # Log sql parameters. For Hibernate 6 version
#    org.hibernate.orm.jdbc.bind: TRACE