version: '3.8'

services:
  gateway-service:
    image: hexhoc/flowing-retail-gateway-service
    container_name: gateway-service
    ports:
      - "8072:8072"
      - "9072:9072"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9072

  product-service:
    image: hexhoc/ecommerce-product-service
    container_name: product-service
    ports:
      - "8000:8000"
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9000

  customer-service:
    image: hexhoc/flowing-retail-customer-service
    container_name: customer-service
    ports:
      - "8040:8040"
      - "9040:9040"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9040

  order-service:
    image: hexhoc/flowing-retail-order-service
    container_name: order-service
    ports:
      - "8050:8050"
      - "9050:9050"
    depends_on:
      - kafka
      - zeebe
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9050

  payment-service:
    image: hexhoc/flowing-retail-payment-service
    container_name: payment-service
    ports:
      - "8020:8020"
      - "9020:9020"
    depends_on:
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9020

  inventory-service:
    image: hexhoc/flowing-retail-inventory-service
    container_name: inventory-service
    ports:
      - "8010:8010"
      - "9010:9010"
    depends_on:
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9010

  shipping-service:
    image: hexhoc/flowing-retail-shipping-service
    container_name: shipping-service
    ports:
      - "8020:8020"
      - "9020:9020"
    depends_on:
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9020

  monitor-service:
    image: hexhoc/flowing-retail-monitor-service
    container_name: monitor-service
    ports:
      - "8095:8095"
      - "9095:9095"
    depends_on:
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9095

  frontend:
    image: hexhoc/flowing-retail-frontend
    container_name: frontend
    ports:
      - "8099:80"
