version: '3.8'

services:
  gateway-service:
    image: hexhoc/flowing-retail-gateway-service
    container_name: gateway-service
    ports:
      - "8072:8072"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  order-service:
    image: hexhoc/flowing-retail-order-service
    container_name: order-service
    ports:
      - "8091:8091"
    depends_on:
      - kafka
      - zeebe
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  payment-service:
    image: hexhoc/flowing-retail-payment-service
    container_name: payment-service
    depends_on:
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  inventory-service:
    image: hexhoc/flowing-retail-inventory-service
    container_name: inventory-service
    depends_on:
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  shipping-service:
    image: hexhoc/flowing-retail-shipping-service
    container_name: shipping-service
    depends_on:
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  monitor-service:
    image: hexhoc/flowing-retail-monitor-service
    container_name: monitor-service
    ports:
      - "8095:8095"
    depends_on:
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  frontend:
    image: hexhoc/flowing-retail-frontend
    container_name: frontend
    ports:
      - "8099:80"

networks:
  default:
    name: third-party_flowing
    external: true