version: '3.8'

services:
  flowing-retail:
    image: hexhoc/flowing-retail
    container_name: flowing-retail
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9090

networks:
  flowing:
    external: true