spring:
  kafka:
    bootstrap-servers: kafka:9092
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://postgresql:5432/shipping_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver