spring:
  application:
    name: shipping-service
  profiles:
    active: dev
  kafka:
    consumer:
      auto-offset-reset: earliest
server:
  port: 8030

logging:
  level:
    org.springframework: INFO
    # Enable hibernate sql log
    org.hibernate.SQL: DEBUG
    # Log sql parameters. For Hibernate 5 version
    org.hibernate.type.descriptor.sql: TRACE
    # Log sql parameters. For Hibernate 6 version
#    org.hibernate.orm.jdbc.bind: TRACE