custom:
  flowingretail:
    customer-service:
      host: http://customer-service:8040
spring:
  kafka:
    bootstrap-servers: kafka:9092
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://postgres:5432/order_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
zeebe:
  client:
    broker:
      gateway-address: zeebe:26500