spring:
  application:
    name: order-service
  kafka:
    consumer:
      auto-offset-reset: earliest
  profiles:
    active: dev
server:
  port: 8050
zeebe:
  client:
    security:
      plaintext: true

logging:
  level:
    org.springframework: INFO
    # Enable hibernate sql log
    org.hibernate.SQL: DEBUG
    # Log sql parameters. For Hibernate 5 version
    org.hibernate.type.descriptor.sql: TRACE
    # Log sql parameters. For Hibernate 6 version
#    org.hibernate.orm.jdbc.bind: TRACE