custom:
  flowingretail:
    customer-service:
      host: http://localhost:8040
spring:
  kafka:
    bootstrap-servers: localhost:29092
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: validate
#    properties:
#      hibernate:
#        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/order_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver